Update JenkinsFile

diff --git a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
--- a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
+++ b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
@@ -112,32 +112,32 @@ spec:
                     }
                 }
             }
-        }
+        }withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
+    sh '''
+        git config user.email "fasilmubarak07@gmail.com"
+        git config user.name "fasil7170"
 
-        stage('Update Deployment File') {
-            environment {
-                GIT_REPO_NAME = "Jenkins-Zero-To-Hero"
-                GIT_USER_NAME = "iam-veeramalla"
-            }
-            steps {
-                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
-                    sh '''
-                        git config user.email "abhishek.xyz@gmail.com"
-                        git config user.name "Abhishek Veeramalla"
+        git checkout main
 
-                        BUILD_NUMBER=${BUILD_NUMBER}
-                        sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
+        BUILD_NUMBER=${BUILD_NUMBER}
+        FILE_PATH="java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml"
 
-                        git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
-                        if ! git diff --cached --quiet; then
-                            git commit -m "Update deployment image to version ${BUILD_NUMBER}"
-                            git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
-                        else
-                            echo "No changes to commit"
-                        fi
-                    '''
-                }
-            }
-        }
-    }
+        if [ -f "$FILE_PATH" ]; then
+            sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" "$FILE_PATH"
+
+            git add "$FILE_PATH"
+
+            if ! git diff --cached --quiet; then
+                git commit -m "Update deployment image to version ${BUILD_NUMBER}"
+                git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
+            else
+                echo "No changes to commit"
+            fi
+        else
+            echo "Deployment file not found!"
+            exit 1
+        fi
+    '''
 }
+
+       
